version: '3.10.2'

services:
 web:
  build:
   context: .
  ports:
  - 8000:8000
  expose:
   - 8000:8000
  volumes:
  - ./:/app

 mysqldb:
  image: mysql:5.7
  ports:
  - 3306:3306
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql
